name: Build, execute tests and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js 18x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Start the app
      run: npm run start &
    - name: Execute unit tests
      run: npm run test:unit
    - name: Install playwright browsers
      run: npx playwright install
    - name: Execute ui tests
      run: npm run test:ui
    - name: Print softuni username
      run: echo 'mihailp123'
  deploy:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to production
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
        api-key: ${{ secrets.MY_RENDER_API_KEY }}
        wait-for-success: true
